version: "2"

services:
    postgresql:
        image: postgres:alpine
        container_name: ${CONTAINER_PREFIX}.postgresql
        ports:
            - ${POSTGRES_PORT}:5432
        volumes:
            - ./postgresql/data:/var/lib/postgresql/data
            - ./logs/postgresql/:/var/log/postgresql
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
    app:
        build: ./app
        container_name: ${CONTAINER_PREFIX}.app
        volumes:
            - ./app:/var/www/app
    php-fpm:
        build: ./php-fpm
        container_name: ${CONTAINER_PREFIX}.php
        volumes_from:
            - app
        volumes:
            - ./php-fpm/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
    nginx:
        build: ./nginx
        container_name: ${CONTAINER_PREFIX}.nginx
        ports:
            - "${NGINX_PORT}:80"
        volumes_from:
            - app
        volumes:
            - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
            - ./nginx/conf.d:/etc/nginx/conf.d:ro
            - ./logs/nginx/:/var/log/nginx
    mailDev:
        image: djfarrelly/maildev
        container_name: ${CONTAINER_PREFIX}.maildev
        ports:
            - "${MAIL_DEV_PORT}:80"